function sqlQuote(value) {
  if (value === null || value === undefined) return 'NULL';
  const str = String(value).replace(/'/g, "''");
  return `'${str}'`;
}

function num(value, fallback = 0) {
  const n = Number(value);
  return Number.isFinite(n) ? n : fallback;
}

function toSqlNumber(value, precision = 4) {
  return num(value, 0).toFixed(precision);
}

function buildTargetsSql({
  profileName,
  cycleName,
  totalGoal,
  monthWeights,
  weekWeights,
  regionCoefficients,
  stores,
  startDate,
  endDate,
  createdBy = 'admin'
}) {
  const lines = [];

  lines.push('-- Generated by Targets Planner UI');
  lines.push('begin;');
  lines.push('');

  lines.push('with profile_row as (');
  lines.push('  insert into target_profiles (profile_name, description, is_default)');
  lines.push(`  values (${sqlQuote(profileName)}, ${sqlQuote('Generated from admin planner')}, false)`);
  lines.push('  returning id');
  lines.push(')');
  lines.push('insert into target_profile_month_weights (profile_id, month_no, weight_percent)');
  lines.push('select profile_row.id, v.month_no, v.weight_percent');
  lines.push('from profile_row');
  lines.push('cross join (values');

  const monthRows = Object.keys(monthWeights)
    .map((monthNo) => `  (${Number(monthNo)}, ${toSqlNumber(monthWeights[monthNo])})`)
    .join(',\n');

  lines.push(monthRows);
  lines.push(') as v(month_no, weight_percent);');
  lines.push('');

  lines.push('with profile_ref as (');
  lines.push(`  select id from target_profiles where profile_name = ${sqlQuote(profileName)} order by id desc limit 1`);
  lines.push(')');
  lines.push('insert into target_profile_week_weights (profile_id, week_no, weight_percent)');
  lines.push('select profile_ref.id, v.week_no, v.weight_percent');
  lines.push('from profile_ref');
  lines.push('cross join (values');

  const weekRows = Object.keys(weekWeights)
    .map((weekNo) => `  (${Number(weekNo)}, ${toSqlNumber(weekWeights[weekNo])})`)
    .join(',\n');

  lines.push(weekRows);
  lines.push(') as v(week_no, weight_percent);');
  lines.push('');

  lines.push('-- upsert regions');
  Object.entries(regionCoefficients).forEach(([region, coeff]) => {
    lines.push(
      `insert into regions (region_code, region_name, weight_coeff)` +
      ` values (${sqlQuote(region.toUpperCase())}, ${sqlQuote(region)}, ${toSqlNumber(coeff)})` +
      ' on conflict (region_code) do update set' +
      ` region_name = excluded.region_name, weight_coeff = excluded.weight_coeff;`
    );
  });
  lines.push('');

  lines.push('-- upsert stores');
  stores.forEach((store) => {
    const storeCode = (store.name || `STORE-${store.id}`).toUpperCase().replace(/[^A-Z0-9]+/g, '_').replace(/^_|_$/g, '').slice(0, 40) || `STORE_${store.id}`;
    lines.push('insert into stores (region_id, store_code, store_name, weight_coeff, has_promoter, promoter_coeff, is_active)');
    lines.push('select');
    lines.push('  r.id,');
    lines.push(`  ${sqlQuote(storeCode)},`);
    lines.push(`  ${sqlQuote(store.name)},`);
    lines.push(`  ${toSqlNumber(store.storeCoeff)},`);
    lines.push(`  ${store.hasPromoter ? 'true' : 'false'},`);
    lines.push(`  ${toSqlNumber(store.promoterCoeff)},`);
    lines.push('  true');
    lines.push('from regions r');
    lines.push(`where r.region_code = ${sqlQuote(String(store.region).toUpperCase())}`);
    lines.push('on conflict (store_code) do update set');
    lines.push('  region_id = excluded.region_id,');
    lines.push('  store_name = excluded.store_name,');
    lines.push('  weight_coeff = excluded.weight_coeff,');
    lines.push('  has_promoter = excluded.has_promoter,');
    lines.push('  promoter_coeff = excluded.promoter_coeff,');
    lines.push('  is_active = excluded.is_active;');
  });
  lines.push('');

  lines.push('-- target cycle');
  lines.push('insert into target_cycles (cycle_name, profile_id, total_goal, start_date, end_date, status, created_by)');
  lines.push('select');
  lines.push(`  ${sqlQuote(cycleName)},`);
  lines.push('  p.id,');
  lines.push(`  ${num(totalGoal, 0).toFixed(2)},`);
  lines.push(`  ${sqlQuote(startDate)},`);
  lines.push(`  ${sqlQuote(endDate)},`);
  lines.push("  'draft',");
  lines.push(`  ${sqlQuote(createdBy)}`);
  lines.push('from target_profiles p');
  lines.push(`where p.profile_name = ${sqlQuote(profileName)}`);
  lines.push('order by p.id desc');
  lines.push('limit 1;');
  lines.push('');

  lines.push('commit;');

  return lines.join('\n');
}

export { buildTargetsSql };
